import type { Metadata } from "next";
import "./globals.css";
import LoadUserClient from "@/components/LoadUserClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <LoadUserClient />
        {children}
      </body>
    </html>
  );
}
